import { Product } from "./schema";

/**
 * Mock data for development and demo purposes
 * This data will be used when Sanity is not connected
 */
export const mockProducts: Product[] = [
  // Biến tần
  {
    _id: "1",
    title: "Biến tần Siemens SINAMICS V20",
    slug: { current: "bien-tan-siemens-v20" },
    category: "bien-tan",
    brand: "Siemens",
    price: 8500000,
    originalPrice: 9500000,
    specs: [
      { label: "Công suất", value: "0.37 - 30 kW" },
      { label: "Điện áp", value: "1AC 200-240V / 3AC 380-480V" },
      { label: "Tần số", value: "0 - 550 Hz" },
      { label: "Giao tiếp", value: "USS, Modbus RTU" },
    ],
    description: "Biến tần Siemens V20 là dòng biến tần kinh tế, dễ sử dụng cho các ứng dụng bơm, quạt và băng tải cơ bản.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "2",
    title: "Biến tần Siemens G120C",
    slug: { current: "bien-tan-siemens-g120c" },
    category: "bien-tan",
    brand: "Siemens",
    price: 15500000,
    originalPrice: 17000000,
    specs: [
      { label: "Công suất", value: "0.55 - 132 kW" },
      { label: "Điện áp", value: "3AC 380-480V" },
      { label: "Tần số", value: "0 - 550 Hz" },
      { label: "Giao tiếp", value: "PROFINET, PROFIBUS" },
    ],
    description: "Biến tần G120C compact với Safety Integrated, lý tưởng cho các ứng dụng công nghiệp đòi hỏi độ tin cậy cao.",
    tag: "best-seller",
    inStock: true,
  },
  {
    _id: "3",
    title: "Biến tần ABB ACS580",
    slug: { current: "bien-tan-abb-acs580" },
    category: "bien-tan",
    brand: "ABB",
    price: 12800000,
    originalPrice: 14000000,
    specs: [
      { label: "Công suất", value: "0.75 - 500 kW" },
      { label: "Điện áp", value: "3AC 380-480V" },
      { label: "IP", value: "IP21 / IP55" },
      { label: "Giao tiếp", value: "Modbus, PROFIBUS, EtherNet/IP" },
    ],
    description: "ACS580 là biến tần đa năng của ABB với giao diện người dùng trực quan và khả năng điều khiển chính xác.",
    tag: "new",
    inStock: true,
  },
  {
    _id: "4",
    title: "Biến tần ABB ACS880",
    slug: { current: "bien-tan-abb-acs880" },
    category: "bien-tan",
    brand: "ABB",
    price: 28500000,
    originalPrice: 32000000,
    specs: [
      { label: "Công suất", value: "0.55 - 6000 kW" },
      { label: "Điện áp", value: "3AC 380-690V" },
      { label: "IP", value: "IP21 / IP55" },
      { label: "Giao tiếp", value: "Đầy đủ các chuẩn công nghiệp" },
    ],
    description: "ACS880 là biến tần cao cấp nhất của ABB với Direct Torque Control (DTC) và khả năng tích hợp Safety.",
    inStock: true,
  },
  {
    _id: "5",
    title: "Biến tần Mitsubishi FR-E840",
    slug: { current: "bien-tan-mitsubishi-fr-e840" },
    category: "bien-tan",
    brand: "Mitsubishi",
    price: 9200000,
    specs: [
      { label: "Công suất", value: "0.4 - 15 kW" },
      { label: "Điện áp", value: "3AC 380-480V" },
      { label: "Tính năng", value: "Tiết kiệm năng lượng OEC" },
      { label: "Giao tiếp", value: "RS-485, CC-Link" },
    ],
    description: "FR-E840 là biến tần compact của Mitsubishi với tính năng tiết kiệm năng lượng vượt trội.",
    tag: "best-seller",
    inStock: true,
  },
  {
    _id: "6",
    title: "Biến tần Delta VFD-E",
    slug: { current: "bien-tan-delta-vfd-e" },
    category: "bien-tan",
    brand: "Delta",
    price: 4500000,
    originalPrice: 5200000,
    specs: [
      { label: "Công suất", value: "0.2 - 22 kW" },
      { label: "Điện áp", value: "1AC/3AC 200-240V, 3AC 380-480V" },
      { label: "Tần số", value: "0.1 - 600 Hz" },
      { label: "Giao tiếp", value: "Modbus RTU" },
    ],
    description: "VFD-E là dòng biến tần kinh tế của Delta, phù hợp cho các ứng dụng công nghiệp nhẹ và HVAC.",
    tag: "hot",
    inStock: true,
  },

  // PLC & HMI
  {
    _id: "7",
    title: "PLC Siemens S7-1200",
    slug: { current: "plc-siemens-s7-1200" },
    category: "plc-hmi",
    brand: "Siemens",
    price: 7800000,
    specs: [
      { label: "CPU", value: "1211C, 1212C, 1214C, 1215C, 1217C" },
      { label: "I/O", value: "Tối đa 284 DI/DO" },
      { label: "Bộ nhớ", value: "Tối đa 150KB" },
      { label: "Giao tiếp", value: "PROFINET, RS-485" },
    ],
    description: "S7-1200 là dòng PLC compact của Siemens, lý tưởng cho tự động hóa máy móc và sản xuất quy mô vừa.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "8",
    title: "PLC Siemens S7-1500",
    slug: { current: "plc-siemens-s7-1500" },
    category: "plc-hmi",
    brand: "Siemens",
    price: 25000000,
    originalPrice: 28000000,
    specs: [
      { label: "CPU", value: "1511, 1513, 1515, 1516, 1517, 1518" },
      { label: "I/O", value: "Không giới hạn" },
      { label: "Bộ nhớ", value: "Tối đa 10MB" },
      { label: "Giao tiếp", value: "PROFINET, PROFIBUS, OPC UA" },
    ],
    description: "S7-1500 là PLC cao cấp của Siemens với hiệu suất xuất sắc, tích hợp Security và Safety.",
    tag: "best-seller",
    inStock: true,
  },
  {
    _id: "9",
    title: "PLC Mitsubishi FX5U",
    slug: { current: "plc-mitsubishi-fx5u" },
    category: "plc-hmi",
    brand: "Mitsubishi",
    price: 12500000,
    specs: [
      { label: "CPU", value: "FX5U-32M, 64M, 80M" },
      { label: "I/O", value: "Tối đa 256 điểm" },
      { label: "Bộ nhớ", value: "128KB" },
      { label: "Giao tiếp", value: "Ethernet, RS-485, CC-Link" },
    ],
    description: "FX5U là dòng PLC mới nhất của Mitsubishi với tốc độ xử lý nhanh và khả năng kết nối IoT.",
    tag: "new",
    inStock: true,
  },
  {
    _id: "10",
    title: "PLC Omron CP1E",
    slug: { current: "plc-omron-cp1e" },
    category: "plc-hmi",
    brand: "Omron",
    price: 5200000,
    specs: [
      { label: "CPU", value: "CP1E-N, CP1E-E" },
      { label: "I/O", value: "10 - 60 điểm" },
      { label: "Bộ nhớ", value: "32KB" },
      { label: "Giao tiếp", value: "USB, RS-232/485" },
    ],
    description: "CP1E là PLC nhỏ gọn, kinh tế của Omron cho các ứng dụng điều khiển đơn giản.",
    inStock: true,
  },
  {
    _id: "11",
    title: "HMI Siemens KTP700 Basic",
    slug: { current: "hmi-siemens-ktp700" },
    category: "plc-hmi",
    brand: "Siemens",
    price: 9500000,
    originalPrice: 11000000,
    specs: [
      { label: "Màn hình", value: "7 inch TFT, 800x480" },
      { label: "Touch", value: "Resistive" },
      { label: "Bộ nhớ", value: "10MB" },
      { label: "Giao tiếp", value: "PROFINET, MPI" },
    ],
    description: "KTP700 Basic là HMI cơ bản của Siemens với màn hình cảm ứng 7 inch, dễ lập trình với TIA Portal.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "12",
    title: "HMI Weintek MT8071iE",
    slug: { current: "hmi-weintek-mt8071ie" },
    category: "plc-hmi",
    brand: "Weintek",
    price: 6800000,
    specs: [
      { label: "Màn hình", value: "7 inch TFT, 800x480" },
      { label: "Touch", value: "Resistive" },
      { label: "Bộ nhớ", value: "128MB Flash" },
      { label: "Giao tiếp", value: "Ethernet, RS-232/485, USB" },
    ],
    description: "MT8071iE là HMI phổ biến của Weintek với khả năng kết nối đa dạng các loại PLC.",
    tag: "best-seller",
    inStock: true,
  },

  // Thiết bị đóng cắt
  {
    _id: "13",
    title: "MCCB Schneider NSX100F",
    slug: { current: "mccb-schneider-nsx100f" },
    category: "dong-cat",
    brand: "Schneider",
    price: 3200000,
    specs: [
      { label: "Dòng định mức", value: "100A" },
      { label: "Điện áp", value: "690V AC" },
      { label: "Icu", value: "36kA @ 415V" },
      { label: "Số cực", value: "3P, 4P" },
    ],
    description: "NSX100F là MCCB của Schneider Electric với khả năng cắt cao, phù hợp cho tủ điện công nghiệp.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "14",
    title: "MCCB Schneider NSX250N",
    slug: { current: "mccb-schneider-nsx250n" },
    category: "dong-cat",
    brand: "Schneider",
    price: 5800000,
    originalPrice: 6500000,
    specs: [
      { label: "Dòng định mức", value: "250A" },
      { label: "Điện áp", value: "690V AC" },
      { label: "Icu", value: "50kA @ 415V" },
      { label: "Số cực", value: "3P, 4P" },
    ],
    description: "NSX250N là MCCB công suất lớn của Schneider với các tùy chọn bảo vệ đa dạng.",
    tag: "best-seller",
    inStock: true,
  },
  {
    _id: "15",
    title: "ACB ABB Emax2 E2.2",
    slug: { current: "acb-abb-emax2" },
    category: "dong-cat",
    brand: "ABB",
    price: 45000000,
    specs: [
      { label: "Dòng định mức", value: "800 - 2500A" },
      { label: "Điện áp", value: "690V AC" },
      { label: "Icu", value: "Tối đa 150kA" },
      { label: "Loại", value: "Rút/Cố định" },
    ],
    description: "Emax2 là dòng ACB cao cấp của ABB với khả năng giao tiếp và giám sát thông minh.",
    tag: "new",
    inStock: true,
  },
  {
    _id: "16",
    title: "Contactor Schneider LC1D25",
    slug: { current: "contactor-schneider-lc1d25" },
    category: "dong-cat",
    brand: "Schneider",
    price: 650000,
    specs: [
      { label: "Dòng định mức", value: "25A" },
      { label: "Điện áp cuộn", value: "24V, 110V, 220V, 380V" },
      { label: "Số cực", value: "3P" },
      { label: "Tiếp điểm phụ", value: "1NO+1NC" },
    ],
    description: "LC1D25 là contactor phổ biến của Schneider cho điều khiển động cơ và tải công nghiệp.",
    inStock: true,
  },
  {
    _id: "17",
    title: "MCCB LS SUSOL TD100N",
    slug: { current: "mccb-ls-susol-td100n" },
    category: "dong-cat",
    brand: "LS Electric",
    price: 1800000,
    originalPrice: 2200000,
    specs: [
      { label: "Dòng định mức", value: "16 - 100A" },
      { label: "Điện áp", value: "690V AC" },
      { label: "Icu", value: "50kA @ 415V" },
      { label: "Số cực", value: "3P, 4P" },
    ],
    description: "SUSOL TD100N là MCCB kinh tế của LS Electric với chất lượng cao, phù hợp cho nhiều ứng dụng.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "18",
    title: "Relay nhiệt Schneider LRD21",
    slug: { current: "relay-nhiet-schneider-lrd21" },
    category: "dong-cat",
    brand: "Schneider",
    price: 420000,
    specs: [
      { label: "Dải chỉnh", value: "12 - 18A" },
      { label: "Class", value: "10A" },
      { label: "Chế độ reset", value: "Tự động / Thủ công" },
      { label: "Tiếp điểm", value: "1NO+1NC" },
    ],
    description: "LRD21 là relay nhiệt bảo vệ quá tải cho động cơ, dùng kết hợp với contactor LC1D.",
    inStock: true,
  },

  // Cảm biến
  {
    _id: "19",
    title: "Cảm biến tiệm cận Omron E2E-X5ME1",
    slug: { current: "cam-bien-tiem-can-omron-e2e" },
    category: "cam-bien",
    brand: "Omron",
    price: 580000,
    specs: [
      { label: "Loại", value: "Inductive" },
      { label: "Khoảng cách", value: "5mm" },
      { label: "Ngõ ra", value: "NPN NO" },
      { label: "Nguồn", value: "12-24V DC" },
    ],
    description: "E2E-X5ME1 là cảm biến tiệm cận phát hiện kim loại với độ tin cậy cao, phổ biến trong công nghiệp.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "20",
    title: "Cảm biến quang Sick WL12L-2B530",
    slug: { current: "cam-bien-quang-sick-wl12l" },
    category: "cam-bien",
    brand: "Sick",
    price: 1850000,
    specs: [
      { label: "Loại", value: "Phản xạ gương" },
      { label: "Khoảng cách", value: "0 - 4m" },
      { label: "Ngõ ra", value: "PNP" },
      { label: "Nguồn", value: "10-30V DC" },
    ],
    description: "WL12L là cảm biến quang của Sick với khả năng phát hiện vật thể ở khoảng cách xa.",
    tag: "best-seller",
    inStock: true,
  },
  {
    _id: "21",
    title: "Cảm biến nhiệt độ PT100",
    slug: { current: "cam-bien-nhiet-do-pt100" },
    category: "cam-bien",
    brand: "Autonics",
    price: 320000,
    specs: [
      { label: "Loại", value: "RTD PT100" },
      { label: "Dải đo", value: "-50 ~ 500°C" },
      { label: "Độ chính xác", value: "Class A" },
      { label: "Chiều dài", value: "100mm" },
    ],
    description: "PT100 là cảm biến nhiệt độ chính xác cao, phổ biến trong công nghiệp và lò nhiệt.",
    inStock: true,
  },
  {
    _id: "22",
    title: "Cảm biến áp suất Autonics PSAN-L01CPV",
    slug: { current: "cam-bien-ap-suat-autonics" },
    category: "cam-bien",
    brand: "Autonics",
    price: 2100000,
    originalPrice: 2500000,
    specs: [
      { label: "Dải đo", value: "-100 ~ 100 kPa" },
      { label: "Ngõ ra", value: "1-5V, 4-20mA" },
      { label: "Nguồn", value: "12-24V DC" },
      { label: "Độ chính xác", value: "±1% F.S." },
    ],
    description: "PSAN-L01CPV là cảm biến áp suất số của Autonics với màn hình hiển thị tiện lợi.",
    tag: "new",
    inStock: true,
  },
  {
    _id: "23",
    title: "Encoder Omron E6B2-CWZ6C",
    slug: { current: "encoder-omron-e6b2" },
    category: "cam-bien",
    brand: "Omron",
    price: 1450000,
    specs: [
      { label: "Loại", value: "Incremental" },
      { label: "Độ phân giải", value: "1000 P/R" },
      { label: "Ngõ ra", value: "NPN Open Collector" },
      { label: "Nguồn", value: "5-24V DC" },
    ],
    description: "E6B2-CWZ6C là encoder tăng trưởng của Omron, phổ biến cho đo vị trí và tốc độ.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "24",
    title: "Cảm biến đo khoảng cách Keyence IL-100",
    slug: { current: "cam-bien-khoang-cach-keyence" },
    category: "cam-bien",
    brand: "Keyence",
    price: 8500000,
    specs: [
      { label: "Loại", value: "Laser CMOS" },
      { label: "Dải đo", value: "65 - 95mm" },
      { label: "Độ phân giải", value: "1μm" },
      { label: "Ngõ ra", value: "Analog, RS-232" },
    ],
    description: "IL-100 là cảm biến laser đo khoảng cách chính xác cao của Keyence, dùng trong kiểm tra chất lượng.",
    tag: "new",
    inStock: true,
  },

  // Vật tư tủ điện
  {
    _id: "25",
    title: "Thanh cái đồng 40x4mm",
    slug: { current: "thanh-cai-dong-40x4" },
    category: "vat-tu",
    brand: "HTtech",
    price: 185000,
    specs: [
      { label: "Kích thước", value: "40x4mm" },
      { label: "Chiều dài", value: "1m" },
      { label: "Dòng định mức", value: "300A" },
      { label: "Chất liệu", value: "Đồng đỏ 99.9%" },
    ],
    description: "Thanh cái đồng chất lượng cao cho tủ điện, đạt tiêu chuẩn IEC.",
    inStock: true,
  },
  {
    _id: "26",
    title: "Máng điện nhựa 40x60mm Vanlock",
    slug: { current: "mang-dien-nhua-vanlock" },
    category: "vat-tu",
    brand: "Vanlock",
    price: 42000,
    specs: [
      { label: "Kích thước", value: "40x60mm" },
      { label: "Chiều dài", value: "2m" },
      { label: "Chất liệu", value: "PVC chống cháy" },
      { label: "Màu sắc", value: "Xám" },
    ],
    description: "Máng điện nhựa PVC chống cháy của Vanlock, phổ biến trong tủ điện công nghiệp.",
    tag: "best-seller",
    inStock: true,
  },
  {
    _id: "27",
    title: "Cầu đấu Phoenix UK5N",
    slug: { current: "cau-dau-phoenix-uk5n" },
    category: "vat-tu",
    brand: "Phoenix Contact",
    price: 28000,
    specs: [
      { label: "Dòng định mức", value: "32A" },
      { label: "Tiết diện dây", value: "0.2 - 4mm²" },
      { label: "Điện áp", value: "690V" },
      { label: "Chất liệu", value: "PA 6.6" },
    ],
    description: "UK5N là cầu đấu dạng vít của Phoenix Contact, tiêu chuẩn công nghiệp châu Âu.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "28",
    title: "Đầu cos đồng SC35-8",
    slug: { current: "dau-cos-dong-sc35-8" },
    category: "vat-tu",
    brand: "HTtech",
    price: 8500,
    specs: [
      { label: "Tiết diện", value: "35mm²" },
      { label: "Lỗ bắt vít", value: "M8" },
      { label: "Chất liệu", value: "Đồng mạ thiếc" },
      { label: "Đóng gói", value: "100 cái/bịch" },
    ],
    description: "Đầu cos đồng SC mạ thiếc chất lượng cao, phù hợp cho cáp điện lực.",
    inStock: true,
  },
  {
    _id: "29",
    title: "Dây điện đơn Cadivi CV 4.0mm²",
    slug: { current: "day-dien-cadivi-cv40" },
    category: "vat-tu",
    brand: "Cadivi",
    price: 32000,
    specs: [
      { label: "Tiết diện", value: "4.0mm²" },
      { label: "Ruột dẫn", value: "Đồng đỏ mềm" },
      { label: "Cách điện", value: "PVC" },
      { label: "Điện áp", value: "450/750V" },
    ],
    description: "Dây điện CV Cadivi ruột đồng cách điện PVC, tiêu chuẩn TCVN.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "30",
    title: "Rơ le trung gian Omron MY2N-GS",
    slug: { current: "ro-le-trung-gian-omron-my2n" },
    category: "vat-tu",
    brand: "Omron",
    price: 125000,
    specs: [
      { label: "Số cực", value: "DPDT (2 cặp tiếp điểm)" },
      { label: "Dòng tiếp điểm", value: "5A" },
      { label: "Điện áp cuộn", value: "24V DC / 220V AC" },
      { label: "Socket", value: "PYF08A-E" },
    ],
    description: "MY2N-GS là rơ le trung gian phổ biến của Omron, tin cậy trong mạch điều khiển.",
    tag: "best-seller",
    inStock: true,
  },
];

// Get products with optional filtering
export function getMockProducts(category?: string): Product[] {
  if (category && category !== "all") {
    return mockProducts.filter((p) => p.category === category);
  }
  return mockProducts;
}

// Get single product by slug
export function getMockProductBySlug(slug: string): Product | undefined {
  return mockProducts.find((p) => p.slug.current === slug);
}

// Get related products (same category, excluding current)
export function getRelatedProducts(product: Product, limit: number = 4): Product[] {
  return mockProducts
    .filter((p) => p.category === product.category && p._id !== product._id)
    .slice(0, limit);
}
