import { Product } from "./schema";

export const mockProducts: Product[] = [
  // Biến tần
  {
    _id: "1",
    title: "Biến tần Siemens SINAMICS V20 0.75kW 1P",
    slug: { current: "bien-tan-siemens-v20-075kw" },
    category: "bien-tan",
    brand: "Siemens",
    price: 2379000,
    originalPrice: 2800000,
    specs: [
      { label: "Model", value: "6SL3210-5BB17-5UV1" },
      { label: "Công suất", value: "0.75 kW" },
      { label: "Điện áp vào", value: "1AC 220-240V" },
      { label: "Tần số ra", value: "0 - 550 Hz" },
      { label: "Giao tiếp", value: "USS, Modbus RTU" },
    ],
    description: "Biến tần Siemens V20 0.75kW 1 pha 220V — dòng kinh tế, dễ vận hành, tích hợp màn hình hiển thị, phù hợp cho bơm, quạt, băng tải nhỏ.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "2",
    title: "Biến tần Siemens SINAMICS G120C 1.5kW",
    slug: { current: "bien-tan-siemens-g120c-15kw" },
    category: "bien-tan",
    brand: "Siemens",
    price: 9800000,
    originalPrice: 11500000,
    specs: [
      { label: "Model", value: "6SL3210-1KE15-8AF2" },
      { label: "Công suất", value: "1.5 kW" },
      { label: "Điện áp vào", value: "3AC 380-480V" },
      { label: "Safety", value: "STO (Safe Torque Off)" },
      { label: "Giao tiếp", value: "PROFINET, PROFIBUS, USS" },
    ],
    description: "Biến tần G120C compact tích hợp Safety STO, lý tưởng cho ứng dụng công nghiệp đòi hỏi độ tin cậy cao và tiết kiệm không gian tủ điện.",
    tag: "best-seller",
    inStock: true,
  },
  {
    _id: "3",
    title: "Biến tần ABB ACS580 0.75kW",
    slug: { current: "bien-tan-abb-acs580-075kw" },
    category: "bien-tan",
    brand: "ABB",
    price: 7400000,
    originalPrice: 14429000,
    specs: [
      { label: "Model", value: "ACS580-01-02A7-4" },
      { label: "Công suất", value: "0.75 kW" },
      { label: "Điện áp vào", value: "3AC 380-480V" },
      { label: "IP", value: "IP21" },
      { label: "Giao tiếp", value: "Modbus RTU, EtherNet/IP (tùy chọn)" },
    ],
    description: "Biến tần ABB ACS580 đa năng với bảng điều khiển trực quan, hỗ trợ điều khiển vô hướng và vector — lý tưởng cho bơm, quạt, máy nén.",
    tag: "new",
    inStock: true,
  },
  {
    _id: "4",
    title: "Biến tần ABB ACS880 0.75kW",
    slug: { current: "bien-tan-abb-acs880-075kw" },
    category: "bien-tan",
    brand: "ABB",
    price: 13500000,
    originalPrice: 16000000,
    specs: [
      { label: "Model", value: "ACS880-01-02A4-3" },
      { label: "Công suất", value: "0.75 kW" },
      { label: "Điện áp vào", value: "3AC 380-480V" },
      { label: "Điều khiển", value: "DTC — Direct Torque Control" },
      { label: "Safety", value: "STO, SS1, SLS tích hợp" },
    ],
    description: "ACS880 là biến tần cao cấp của ABB với công nghệ DTC, đáp ứng mọi ứng dụng truyền động từ bơm đến máy CNC, hỗ trợ toàn bộ chuẩn fieldbus.",
    inStock: true,
  },
  {
    _id: "5",
    title: "Biến tần Mitsubishi FR-E840 0.4kW",
    slug: { current: "bien-tan-mitsubishi-fr-e840-04kw" },
    category: "bien-tan",
    brand: "Mitsubishi",
    price: 4200000,
    specs: [
      { label: "Model", value: "FR-E840-0.4K-E" },
      { label: "Công suất", value: "0.4 kW" },
      { label: "Điện áp vào", value: "3AC 380-480V" },
      { label: "Tính năng", value: "OEC — Optimal Excitation Control" },
      { label: "Giao tiếp", value: "RS-485 (Modbus RTU, CC-Link)" },
    ],
    description: "FR-E840 — biến tần compact Mitsubishi thế hệ mới, tiết kiệm năng lượng vượt trội nhờ OEC, thích hợp cho băng tải, quạt công nghiệp.",
    tag: "best-seller",
    inStock: true,
  },
  {
    _id: "6",
    title: "Biến tần Delta VFD007E21A 0.75kW",
    slug: { current: "bien-tan-delta-vfd007e21a" },
    category: "bien-tan",
    brand: "Delta",
    price: 2200000,
    originalPrice: 2600000,
    specs: [
      { label: "Model", value: "VFD007E21A" },
      { label: "Công suất", value: "0.75 kW" },
      { label: "Điện áp vào", value: "1AC 200-240V" },
      { label: "Tần số ra", value: "0.1 - 600 Hz" },
      { label: "Giao tiếp", value: "RS-485 Modbus RTU" },
    ],
    description: "Delta VFD-E 0.75kW 1 pha — lựa chọn kinh tế phổ biến cho SME Việt Nam, hỗ trợ bơm nước, quạt thông gió, máy móc nhẹ.",
    tag: "hot",
    inStock: true,
  },

  // PLC & HMI
  {
    _id: "7",
    title: "PLC Siemens S7-1200 CPU 1214C DC/DC/DC",
    slug: { current: "plc-siemens-s7-1200-cpu1214c" },
    category: "plc-hmi",
    brand: "Siemens",
    price: 5600000,
    originalPrice: 6500000,
    specs: [
      { label: "Model", value: "6ES7214-1AG40-0XB0" },
      { label: "DI/DO tích hợp", value: "14 DI / 10 DO" },
      { label: "AI tích hợp", value: "2 AI (0-10V)" },
      { label: "Bộ nhớ", value: "100 KB chương trình + 4 MB dữ liệu" },
      { label: "Giao tiếp", value: "1× PROFINET, 1× RS-485" },
    ],
    description: "S7-1200 CPU 1214C — PLC compact Siemens phổ biến nhất tại Việt Nam, lập trình bằng TIA Portal, hỗ trợ PROFINET và mở rộng I/O linh hoạt.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "8",
    title: "PLC Siemens S7-1500 CPU 1511-1 PN",
    slug: { current: "plc-siemens-s7-1500-cpu1511" },
    category: "plc-hmi",
    brand: "Siemens",
    price: 13911000,
    originalPrice: 16500000,
    specs: [
      { label: "Model", value: "6ES7511-1AK02-0AB0" },
      { label: "Bộ nhớ làm việc", value: "150 KB" },
      { label: "Chu kỳ bit", value: "60 ns" },
      { label: "Giao tiếp", value: "2× PROFINET IRT, OPC UA" },
      { label: "Tính năng", value: "Security tích hợp, ProDiag" },
    ],
    description: "S7-1500 CPU 1511-1 PN — PLC hiệu suất cao của Siemens với OPC UA, bảo mật tích hợp, phù hợp cho dây chuyền sản xuất yêu cầu tốc độ phản hồi nhanh.",
    tag: "best-seller",
    inStock: true,
  },
  {
    _id: "9",
    title: "PLC Mitsubishi FX5U-32MT/ES",
    slug: { current: "plc-mitsubishi-fx5u-32mt" },
    category: "plc-hmi",
    brand: "Mitsubishi",
    price: 7500000,
    originalPrice: 8800000,
    specs: [
      { label: "Model", value: "FX5U-32MT/ES" },
      { label: "I/O tích hợp", value: "16 DI / 16 DO Transistor" },
      { label: "Bộ nhớ", value: "64 KB chương trình" },
      { label: "Tốc độ xử lý", value: "34 ns/lệnh cơ bản" },
      { label: "Giao tiếp", value: "Ethernet, RS-485, USB" },
    ],
    description: "FX5U — thế hệ PLC compact mới nhất của Mitsubishi, tốc độ xử lý vượt trội, hỗ trợ CC-Link IE Field Basic và kết nối IoT trực tiếp.",
    tag: "new",
    inStock: true,
  },
  {
    _id: "10",
    title: "PLC Omron CP1E-N20DR-A",
    slug: { current: "plc-omron-cp1e-n20dr" },
    category: "plc-hmi",
    brand: "Omron",
    price: 4800000,
    specs: [
      { label: "Model", value: "CP1E-N20DR-A" },
      { label: "I/O tích hợp", value: "12 DI / 8 DO Relay" },
      { label: "Bộ nhớ", value: "8 KB chương trình" },
      { label: "Nguồn", value: "AC 100-240V" },
      { label: "Giao tiếp", value: "USB, RS-232" },
    ],
    description: "CP1E-N20 — PLC nhỏ gọn Omron với relay output, giải pháp tự động hoá kinh tế cho máy đóng gói, băng tải, thiết bị bán tự động.",
    inStock: true,
  },
  {
    _id: "11",
    title: "HMI Siemens KTP700 Basic PN",
    slug: { current: "hmi-siemens-ktp700-basic-pn" },
    category: "plc-hmi",
    brand: "Siemens",
    price: 9500000,
    originalPrice: 11000000,
    specs: [
      { label: "Model", value: "6AV2123-2GB03-0AX0" },
      { label: "Màn hình", value: "7\" TFT 800×480, 65.536 màu" },
      { label: "Cảm ứng", value: "Resistive + 8 phím cứng" },
      { label: "Bộ nhớ", value: "10 MB user memory" },
      { label: "Giao tiếp", value: "1× PROFINET, MPI/PROFIBUS" },
    ],
    description: "KTP700 Basic PN — HMI 7 inch phổ biến nhất của Siemens, lập trình bằng WinCC Basic (TIA Portal), cấu hình nhanh, hỗ trợ đa ngôn ngữ.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "12",
    title: "HMI Weintek MT8071iE",
    slug: { current: "hmi-weintek-mt8071ie" },
    category: "plc-hmi",
    brand: "Weintek",
    price: 6800000,
    specs: [
      { label: "Màn hình", value: "7\" TFT 800×480, 65.536 màu" },
      { label: "Cảm ứng", value: "Resistive" },
      { label: "CPU", value: "Cortex-A8 600 MHz" },
      { label: "Flash", value: "128 MB" },
      { label: "Giao tiếp", value: "Ethernet, RS-232/485/422, USB host" },
    ],
    description: "MT8071iE — HMI 7 inch Weintek kết nối được với hơn 500 loại PLC/biến tần, phần mềm EasyBuilder Pro miễn phí, giá thành cạnh tranh.",
    tag: "best-seller",
    inStock: true,
  },

  // Thiết bị đóng cắt
  {
    _id: "13",
    title: "MCCB Schneider NSX100F 3P 100A TM100D",
    slug: { current: "mccb-schneider-nsx100f-3p-100a" },
    category: "dong-cat",
    brand: "Schneider",
    price: 3900000,
    specs: [
      { label: "Model", value: "LV429863" },
      { label: "Dòng định mức", value: "100A" },
      { label: "Icu @ 415V", value: "36 kA" },
      { label: "Điện áp", value: "690V AC / 250V DC" },
      { label: "Số cực", value: "3P" },
    ],
    description: "NSX100F TM100D — aptomat khối Schneider dòng cắt 36kA, bảo vệ quá tải và ngắn mạch, tiêu chuẩn IEC 60947-2, phổ biến trong tủ MCC.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "14",
    title: "MCCB Schneider NSX250N 3P 250A TM250D",
    slug: { current: "mccb-schneider-nsx250n-3p-250a" },
    category: "dong-cat",
    brand: "Schneider",
    price: 7500000,
    originalPrice: 8800000,
    specs: [
      { label: "Model", value: "LV431631" },
      { label: "Dòng định mức", value: "250A" },
      { label: "Icu @ 415V", value: "50 kA" },
      { label: "Điện áp", value: "690V AC" },
      { label: "Số cực", value: "3P" },
    ],
    description: "NSX250N TM250D — MCCB 250A cắt 50kA của Schneider, nhiệt từ điều chỉnh được, phù hợp tủ phân phối và bảo vệ tải nặng.",
    tag: "best-seller",
    inStock: true,
  },
  {
    _id: "15",
    title: "ACB ABB Emax2 E2.2B 2000A",
    slug: { current: "acb-abb-emax2-e22b-2000a" },
    category: "dong-cat",
    brand: "ABB",
    price: 45000000,
    specs: [
      { label: "Model", value: "E2.2B 2000A 3P F HR" },
      { label: "Dòng định mức", value: "2000A" },
      { label: "Icu @ 415V", value: "85 kA" },
      { label: "Loại", value: "Cố định (Fixed)" },
      { label: "Giao tiếp", value: "Ekip Touch LSIG + Modbus" },
    ],
    description: "ACB Emax2 E2.2B ABB với relay bảo vệ kỹ thuật số Ekip Touch, giám sát năng lượng thời gian thực, kết nối Modbus/PROFIBUS.",
    tag: "new",
    inStock: true,
  },
  {
    _id: "16",
    title: "Contactor Schneider LC1D25M7 25A",
    slug: { current: "contactor-schneider-lc1d25m7" },
    category: "dong-cat",
    brand: "Schneider",
    price: 730000,
    specs: [
      { label: "Model", value: "LC1D25M7" },
      { label: "Dòng AC-3 @ 400V", value: "25A (11 kW)" },
      { label: "Điện áp cuộn", value: "220V AC 50/60Hz" },
      { label: "Tiếp điểm phụ", value: "1NO + 1NC" },
      { label: "Tuổi thọ điện", value: "1.000.000 lần" },
    ],
    description: "LC1D25M7 — khởi động từ Schneider 25A cuộn 220V, kết hợp với relay nhiệt LRD để bảo vệ động cơ 3 pha đến 11kW.",
    inStock: true,
  },
  {
    _id: "17",
    title: "MCCB LS SUSOL TD100N 3P 100A",
    slug: { current: "mccb-ls-susol-td100n-3p-100a" },
    category: "dong-cat",
    brand: "LS Electric",
    price: 1800000,
    originalPrice: 2200000,
    specs: [
      { label: "Model", value: "TD100N FMU 100A" },
      { label: "Dòng định mức", value: "100A" },
      { label: "Icu @ 415V", value: "50 kA" },
      { label: "Điện áp", value: "690V AC" },
      { label: "Số cực", value: "3P" },
    ],
    description: "MCCB LS SUSOL TD100N — aptomat khối Hàn Quốc 100A cắt 50kA, giá thành tốt, chứng nhận IEC 60947-2, được dùng rộng rãi trong dự án dân dụng và công nghiệp.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "18",
    title: "Relay nhiệt Schneider LRD21 12-18A",
    slug: { current: "relay-nhiet-schneider-lrd21" },
    category: "dong-cat",
    brand: "Schneider",
    price: 420000,
    specs: [
      { label: "Model", value: "LRD21" },
      { label: "Dải chỉnh dòng", value: "12 - 18A" },
      { label: "Class", value: "10A" },
      { label: "Reset", value: "Tự động / Thủ công" },
      { label: "Tiếp điểm", value: "1NO + 1NC" },
    ],
    description: "LRD21 — relay nhiệt bảo vệ quá tải động cơ 3 pha, dải 12-18A, lắp thẳng vào contactor LC1D09~D25, reset tay hoặc tự động.",
    inStock: true,
  },

  // Cảm biến
  {
    _id: "19",
    title: "Cảm biến tiệm cận Omron E2E-X5ME1 M18",
    slug: { current: "cam-bien-tiem-can-omron-e2e-x5me1" },
    category: "cam-bien",
    brand: "Omron",
    price: 580000,
    specs: [
      { label: "Model", value: "E2E-X5ME1" },
      { label: "Loại", value: "Inductive (cảm ứng từ)" },
      { label: "Khoảng cách phát hiện", value: "5mm" },
      { label: "Ngõ ra", value: "NPN NO, 3 dây" },
      { label: "Nguồn", value: "10-30V DC" },
    ],
    description: "E2E-X5ME1 — cảm biến tiệm cận M18 của Omron phát hiện kim loại sắt trong 5mm, vỏ inox IP67, chịu dầu nhớt, phổ biến nhất trong ngành.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "20",
    title: "Cảm biến quang Sick WL12L-2B530",
    slug: { current: "cam-bien-quang-sick-wl12l-2b530" },
    category: "cam-bien",
    brand: "Sick",
    price: 1850000,
    specs: [
      { label: "Model", value: "WL12L-2B530" },
      { label: "Loại", value: "Phản xạ gương (Retroreflective)" },
      { label: "Tầm phát hiện", value: "0.1 - 4m" },
      { label: "Ngõ ra", value: "PNP NO/NC" },
      { label: "Nguồn", value: "10-30V DC" },
    ],
    description: "WL12L-2B530 — cảm biến quang phản xạ gương Sick, tầm 4m, gương MSE45, chịu được môi trường bụi bẩn, dùng rộng trên băng tải đóng gói.",
    tag: "best-seller",
    inStock: true,
  },
  {
    _id: "21",
    title: "Cảm biến nhiệt độ Autonics PT100 100mm",
    slug: { current: "cam-bien-nhiet-do-autonics-pt100" },
    category: "cam-bien",
    brand: "Autonics",
    price: 320000,
    specs: [
      { label: "Model", value: "NP100-100" },
      { label: "Loại", value: "RTD Pt100 3 dây" },
      { label: "Dải đo", value: "-50 ~ 500°C" },
      { label: "Độ chính xác", value: "Class A (±0.15°C + 0.002|t|)" },
      { label: "Chiều dài nhúng", value: "100mm, φ6mm" },
    ],
    description: "PT100 3 dây Autonics NP100-100 — cảm biến nhiệt độ chuẩn công nghiệp, lắp vặn M12, phù hợp lò nhiệt, đường ống, bể nước nóng.",
    inStock: true,
  },
  {
    _id: "22",
    title: "Cảm biến áp suất Autonics PSAN-L01CPV",
    slug: { current: "cam-bien-ap-suat-autonics-psan" },
    category: "cam-bien",
    brand: "Autonics",
    price: 2100000,
    originalPrice: 2500000,
    specs: [
      { label: "Model", value: "PSAN-L01CPV" },
      { label: "Dải đo", value: "-0.1 ~ 1.0 MPa" },
      { label: "Ngõ ra", value: "1-5V DC + NPN" },
      { label: "Nguồn", value: "12-24V DC" },
      { label: "Độ chính xác", value: "±1.0% F.S." },
    ],
    description: "PSAN-L01CPV — cảm biến áp suất số Autonics màn hình LED 4 số, 2 ngõ ra PNP + analog 1-5V, dùng cho khí nén và chất lỏng không ăn mòn.",
    tag: "new",
    inStock: true,
  },
  {
    _id: "23",
    title: "Encoder Omron E6B2-CWZ6C 1000P/R",
    slug: { current: "encoder-omron-e6b2-cwz6c-1000" },
    category: "cam-bien",
    brand: "Omron",
    price: 1200000,
    specs: [
      { label: "Model", value: "E6B2-CWZ6C 1000P/R" },
      { label: "Loại", value: "Incremental, 3 pha A/B/Z" },
      { label: "Độ phân giải", value: "1000 xung/vòng" },
      { label: "Ngõ ra", value: "NPN Open Collector" },
      { label: "Nguồn", value: "5-24V DC" },
    ],
    description: "E6B2-CWZ6C 1000P/R — encoder tăng dần Omron trục 6mm, tốc độ đến 6000 rpm, dùng đo vị trí và tốc độ cho servo, băng tải, máy in.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "24",
    title: "Cảm biến Laser Keyence IL-100",
    slug: { current: "cam-bien-laser-keyence-il-100" },
    category: "cam-bien",
    brand: "Keyence",
    price: 8500000,
    specs: [
      { label: "Model", value: "IL-100" },
      { label: "Loại", value: "Laser CMOS thu phản xạ" },
      { label: "Dải đo", value: "65 - 95mm (điểm chuẩn 80mm)" },
      { label: "Độ phân giải", value: "1 μm" },
      { label: "Ngõ ra", value: "Analog ±4V / RS-232C" },
    ],
    description: "IL-100 — cảm biến laser đo khoảng cách Keyence chính xác 1μm, dùng kiểm tra độ dày, phát hiện bề mặt, đo vị trí trong dây chuyền kiểm tra chất lượng.",
    tag: "new",
    inStock: true,
  },

  // Vật tư tủ điện
  {
    _id: "25",
    title: "Thanh cái đồng 40×4mm (1m)",
    slug: { current: "thanh-cai-dong-40x4mm-1m" },
    category: "vat-tu",
    brand: "HTtech",
    price: 185000,
    specs: [
      { label: "Kích thước", value: "40 × 4 mm" },
      { label: "Chiều dài", value: "1m/thanh" },
      { label: "Dòng tải", value: "~300A liên tục" },
      { label: "Chất liệu", value: "Đồng đỏ Cu≥99.9%" },
    ],
    description: "Thanh cái đồng đỏ 40×4mm tiêu chuẩn IEC, dùng cho tủ phân phối chính MSB, tủ MCC, chịu dòng 300A liên tục ở 40°C.",
    inStock: true,
  },
  {
    _id: "26",
    title: "Máng cáp nhựa Vanlock 40×60mm (2m)",
    slug: { current: "mang-cap-nhua-vanlock-40x60" },
    category: "vat-tu",
    brand: "Vanlock",
    price: 42000,
    specs: [
      { label: "Kích thước ngoài", value: "40 × 60 mm" },
      { label: "Chiều dài", value: "2m/thanh" },
      { label: "Chất liệu", value: "PVC chống cháy V0" },
      { label: "Màu", value: "Xám RAL 7030" },
    ],
    description: "Máng cáp nhựa PVC Vanlock chống cháy V0 40×60mm — nắp bật dễ đi dây, tiêu chuẩn phổ biến nhất trong tủ điện công nghiệp Việt Nam.",
    tag: "best-seller",
    inStock: true,
  },
  {
    _id: "27",
    title: "Cầu đấu Phoenix Contact UK 5N (1 cái)",
    slug: { current: "cau-dau-phoenix-uk5n" },
    category: "vat-tu",
    brand: "Phoenix Contact",
    price: 28000,
    specs: [
      { label: "Model", value: "UK 5N (3044116)" },
      { label: "Dòng định mức", value: "32A" },
      { label: "Điện áp", value: "800V" },
      { label: "Tiết diện dây", value: "0.2 - 6 mm²" },
      { label: "Tiêu chuẩn", value: "IEC 60947-7-1" },
    ],
    description: "Cầu đấu vít Phoenix Contact UK 5N — chuẩn DIN EN 35, thân PA6.6, tiêu chuẩn châu Âu, bán từng cái hoặc theo hộp 50/100 cái.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "28",
    title: "Đầu cos đồng SC 35-8 (100 cái/bịch)",
    slug: { current: "dau-cos-dong-sc35-8" },
    category: "vat-tu",
    brand: "HTtech",
    price: 8500,
    specs: [
      { label: "Tiết diện cáp", value: "35 mm²" },
      { label: "Lỗ bắt vít", value: "M8" },
      { label: "Chất liệu", value: "Đồng mạ thiếc Sn" },
      { label: "Đóng gói", value: "100 cái/bịch" },
    ],
    description: "Đầu cos đồng mạ thiếc SC 35-8, ép thủy lực, phù hợp cáp điện lực 35mm² kết nối thanh cái và thiết bị đóng cắt. Giá 1 cái.",
    inStock: true,
  },
  {
    _id: "29",
    title: "Dây điện Cadivi CV-4.0 (1m)",
    slug: { current: "day-dien-cadivi-cv40-1m" },
    category: "vat-tu",
    brand: "Cadivi",
    price: 32000,
    specs: [
      { label: "Tiết diện", value: "4.0 mm²" },
      { label: "Ruột dẫn", value: "Đồng mềm bện 7 sợi" },
      { label: "Cách điện", value: "PVC type A" },
      { label: "Điện áp định mức", value: "450/750V" },
      { label: "Tiêu chuẩn", value: "TCVN 6610-3" },
    ],
    description: "Dây điện đơn Cadivi CV-4.0 ruột đồng mềm cách điện PVC — chuẩn TCVN 6610, thường dùng đấu nối trong tủ điện và bảng điện. Bán theo mét.",
    tag: "hot",
    inStock: true,
  },
  {
    _id: "30",
    title: "Rơ le trung gian Omron MY2N-GS 24VDC",
    slug: { current: "ro-le-trung-gian-omron-my2n-gs-24vdc" },
    category: "vat-tu",
    brand: "Omron",
    price: 125000,
    specs: [
      { label: "Model", value: "MY2N-GS DC24" },
      { label: "Tiếp điểm", value: "DPDT — 2 cặp đảo chiều" },
      { label: "Dòng tiếp điểm", value: "5A @ 250V AC" },
      { label: "Điện áp cuộn", value: "24V DC" },
      { label: "Socket", value: "PYF08A-E (bán kèm)" },
    ],
    description: "MY2N-GS 24VDC — rơ le trung gian Omron 2 tầng tiếp điểm, đèn LED báo trạng thái, tuổi thọ cơ 10 triệu lần, dùng trong mạch điều khiển PLC.",
    tag: "best-seller",
    inStock: true,
  },
];

// Get products with optional filtering
export function getMockProducts(category?: string): Product[] {
  if (category && category !== "all") {
    return mockProducts.filter((p) => p.category === category);
  }
  return mockProducts;
}

// Get single product by slug
export function getMockProductBySlug(slug: string): Product | undefined {
  return mockProducts.find((p) => p.slug.current === slug);
}

// Get related products (same category, excluding current)
export function getRelatedProducts(product: Product, limit: number = 4): Product[] {
  return mockProducts
    .filter((p) => p.category === product.category && p._id !== product._id)
    .slice(0, limit);
}
